# Generated by Django 5.2.11 on 2026-02-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortcutLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ссылки')),
                ('target_url', models.URLField(verbose_name='Целевая ссылка')),
                ('short_url', models.URLField(blank=True, verbose_name='Короткая ссылка')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Количество кликов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
            },
        ),
    ]
