# Generated by Django 5.2.11 on 2026-02-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('category', models.CharField(choices=[('seasonal', 'Сезонные вещи'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rent.rent', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Хранимая вещь',
                'verbose_name_plural': 'Хранимые вещи',
            },
        ),
    ]
