# Generated by Django 5.2.11 on 2026-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_storeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='delivery_required',
            field=models.BooleanField(default=False, verbose_name='Требуется доставка'),
        ),
        migrations.AddField(
            model_name='rent',
            name='measurements_required',
            field=models.BooleanField(default=False, verbose_name='Требуются замеры'),
        ),
    ]
