# Generated by Django 5.2.11 on 2026-02-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouses/', verbose_name='Изображение')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Температура')),
                ('ceiling_height', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Высота потолков')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('how_to_reach', models.TextField(blank=True, verbose_name='Как добраться')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Есть парковка')),
                ('near_subway', models.BooleanField(default=False, verbose_name='Рядом с метро')),
                ('rate_per_cubic_meter', models.DecimalField(decimal_places=2, default=0, help_text='Цена за 1 кубический метр в месяц', max_digits=8, verbose_name='Ставка за м³ в месяц')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер бокса')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площадь')),
                ('dimensions', models.CharField(max_length=50, verbose_name='Габариты')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за месяц')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('size_category', models.CharField(blank=True, choices=[('small', 'До 3 м²'), ('medium', 'До 10 м²'), ('large', 'От 10 м²')], max_length=10, verbose_name='Категория размера')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина (м)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ширина (м)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота (м)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
    ]
